# -*- coding: utf-8 -*-
"""pythonlab4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AXADuWEL_ESpBo7KRp0ItDImXk4riFhv

04/14
"""

#q1

userproblem = input("Enter your math problem here: ")

a, b, c = userproblem.split(" ")

a = float(a)
c = float(c)

if b == '+':
  answer = a + c
  print(answer)
elif b == '-':
  answer = a - c
  print(answer)
elif b == '*':
  answer = a * c
  print(answer)
elif b == '/':
  answer = a / c
  print(answer)

#q2

def main():
  time = input("What time is it? (24 hour clock): ")
  convert_time(time)


def convert_time(time):
  hours, minutes = time.split(":")
  hours = float(hours)
  minutes = (float(hours) * 60) + float(minutes)
  time = minutes / 60
  time = float(time)
  if time >= 8.0 and time < 10.0:
    print("Time for reading lessons.")
  elif time >= 10.0 and time < 12.0:
    print("Time for math lessons.")
  elif time >= 12.0 and time < 13.0:
    print("Time for lunch.")
  elif time >= 13.0 and time < 14.0:
    print("Time for music lessons.")

main()